### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by CombatCode** [linnovate/mean-translate#2]
Hi, 
in newest mean.io version server/ dir was moved to packages direcory.
So currently mean-translate is not working correctly.

```
at Object.handle (/home/combat/.dev/urstyle/node_modules/mean-translate/server/routes/index.js:35:21)
```

this line need to be changed from

```
var index = require(process.cwd() + '/server/controllers/index');
```

to

```
var index = require(process.cwd() + '/packages/system/server/controllers/index');
```

Unfortunately I'm not able to send PR with this change at now

**Comment by randwa1k** [comment]
Yes this solves the error I had:

<pre>
        Error: Cannot find module '/home/arrow/app201408app/server/controllers/index'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/arrow/app201408app/node_modules/mean-translate/server/routes/index.js:35:21
    at Layer.handle [as handle_request] (/home/arrow/app201408app/node_modules/express/lib/router/layer.js:76:5)
    at next (/home/arrow/app201408app/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/home/arrow/app201408app/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/home/arrow/app201408app/node_modules/express/lib/router/layer.js:76:5)
    at /home/arrow/app201408app/node_modules/express/lib/router/index.js:227:24
      
</pre>
